import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const BEAST_EXPERIMENTAL = truthy("BEAST_EXPERIMENTAL")
const BEAST_DISABLE_CLAUDE_CODE = truthy("BEAST_DISABLE_CLAUDE_CODE")
const BEAST_DISABLE_CLAUDE_CODE_SKILLS =
  BEAST_DISABLE_CLAUDE_CODE || truthy("BEAST_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["BEAST_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  BEAST_AUTO_SHARE: truthy("BEAST_AUTO_SHARE"),
  BEAST_AUTO_HEAP_SNAPSHOT: truthy("BEAST_AUTO_HEAP_SNAPSHOT"),
  BEAST_GIT_BASH_PATH: process.env["BEAST_GIT_BASH_PATH"],
  BEAST_CONFIG: process.env["BEAST_CONFIG"],
  BEAST_CONFIG_CONTENT: process.env["BEAST_CONFIG_CONTENT"],
  BEAST_DISABLE_AUTOUPDATE: truthy("BEAST_DISABLE_AUTOUPDATE"),
  BEAST_ALWAYS_NOTIFY_UPDATE: truthy("BEAST_ALWAYS_NOTIFY_UPDATE"),
  BEAST_DISABLE_PRUNE: truthy("BEAST_DISABLE_PRUNE"),
  BEAST_DISABLE_TERMINAL_TITLE: truthy("BEAST_DISABLE_TERMINAL_TITLE"),
  BEAST_SHOW_TTFD: truthy("BEAST_SHOW_TTFD"),
  BEAST_PERMISSION: process.env["BEAST_PERMISSION"],
  BEAST_DISABLE_DEFAULT_PLUGINS: truthy("BEAST_DISABLE_DEFAULT_PLUGINS"),
  BEAST_DISABLE_LSP_DOWNLOAD: truthy("BEAST_DISABLE_LSP_DOWNLOAD"),
  BEAST_ENABLE_EXPERIMENTAL_MODELS: truthy("BEAST_ENABLE_EXPERIMENTAL_MODELS"),
  BEAST_DISABLE_AUTOCOMPACT: truthy("BEAST_DISABLE_AUTOCOMPACT"),
  BEAST_DISABLE_MODELS_FETCH: truthy("BEAST_DISABLE_MODELS_FETCH"),
  BEAST_DISABLE_MOUSE: truthy("BEAST_DISABLE_MOUSE"),
  BEAST_DISABLE_CLAUDE_CODE,
  BEAST_DISABLE_CLAUDE_CODE_PROMPT: BEAST_DISABLE_CLAUDE_CODE || truthy("BEAST_DISABLE_CLAUDE_CODE_PROMPT"),
  BEAST_DISABLE_CLAUDE_CODE_SKILLS,
  BEAST_DISABLE_EXTERNAL_SKILLS: truthy("BEAST_DISABLE_EXTERNAL_SKILLS"),
  BEAST_FAKE_VCS: process.env["BEAST_FAKE_VCS"],
  BEAST_SERVER_PASSWORD: process.env["BEAST_SERVER_PASSWORD"],
  BEAST_SERVER_USERNAME: process.env["BEAST_SERVER_USERNAME"],
  BEAST_ENABLE_QUESTION_TOOL: truthy("BEAST_ENABLE_QUESTION_TOOL"),

  // Experimental
  BEAST_EXPERIMENTAL,
  BEAST_EXPERIMENTAL_FILEWATCHER: Config.boolean("BEAST_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  BEAST_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("BEAST_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  BEAST_EXPERIMENTAL_ICON_DISCOVERY: BEAST_EXPERIMENTAL || truthy("BEAST_EXPERIMENTAL_ICON_DISCOVERY"),
  BEAST_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("BEAST_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  BEAST_ENABLE_EXA: truthy("BEAST_ENABLE_EXA") || BEAST_EXPERIMENTAL || truthy("BEAST_EXPERIMENTAL_EXA"),
  BEAST_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("BEAST_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  BEAST_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("BEAST_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  BEAST_EXPERIMENTAL_OXFMT: BEAST_EXPERIMENTAL || truthy("BEAST_EXPERIMENTAL_OXFMT"),
  BEAST_EXPERIMENTAL_LSP_TY: truthy("BEAST_EXPERIMENTAL_LSP_TY"),
  BEAST_EXPERIMENTAL_LSP_TOOL: BEAST_EXPERIMENTAL || truthy("BEAST_EXPERIMENTAL_LSP_TOOL"),
  BEAST_EXPERIMENTAL_PLAN_MODE: BEAST_EXPERIMENTAL || truthy("BEAST_EXPERIMENTAL_PLAN_MODE"),
  BEAST_EXPERIMENTAL_MARKDOWN: !falsy("BEAST_EXPERIMENTAL_MARKDOWN"),
  BEAST_MODELS_URL: process.env["BEAST_MODELS_URL"],
  BEAST_MODELS_PATH: process.env["BEAST_MODELS_PATH"],
  BEAST_DISABLE_EMBEDDED_WEB_UI: truthy("BEAST_DISABLE_EMBEDDED_WEB_UI"),
  BEAST_DB: process.env["BEAST_DB"],
  BEAST_DISABLE_CHANNEL_DB: truthy("BEAST_DISABLE_CHANNEL_DB"),
  BEAST_SKIP_MIGRATIONS: truthy("BEAST_SKIP_MIGRATIONS"),
  BEAST_STRICT_CONFIG_DEPS: truthy("BEAST_STRICT_CONFIG_DEPS"),

  BEAST_WORKSPACE_ID: process.env["BEAST_WORKSPACE_ID"],
  BEAST_EXPERIMENTAL_HTTPAPI: truthy("BEAST_EXPERIMENTAL_HTTPAPI"),
  BEAST_EXPERIMENTAL_WORKSPACES: BEAST_EXPERIMENTAL || truthy("BEAST_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get BEAST_DISABLE_PROJECT_CONFIG() {
    return truthy("BEAST_DISABLE_PROJECT_CONFIG")
  },
  get BEAST_TUI_CONFIG() {
    return process.env["BEAST_TUI_CONFIG"]
  },
  get BEAST_CONFIG_DIR() {
    return process.env["BEAST_CONFIG_DIR"]
  },
  get BEAST_PURE() {
    return truthy("BEAST_PURE")
  },
  get BEAST_PLUGIN_META_FILE() {
    return process.env["BEAST_PLUGIN_META_FILE"]
  },
  get BEAST_CLIENT() {
    return process.env["BEAST_CLIENT"] ?? "cli"
  },
}
